### ISSUE TITLE
Plugin exception in IntelliJ IDEA 2017.1

### ISSUE THREAD

**Issue by yahor-filipchyk** [Thangiee/Freasy-Monad#10]
I've got an exception when trying to write free monads in new version of Intellij which just came out recently. Some updates to Scala plugin where part of this major release. It could be that they've changed some API.

Here is the full version of my installation:
```
IntelliJ IDEA 2017.1
Build #IU-171.3780.107, built on March 22, 2017
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.3
```
Scala plugin version: 
```
2017.1.15
```

Exception stack trace:
```
org.jetbrains.plugins.scala.lang.psi.api.statements.ScFunction.returnType()Lorg/jetbrains/plugins/scala/lang/psi/types/result/TypeResult;
java.lang.NoSuchMethodError: org.jetbrains.plugins.scala.lang.psi.api.statements.ScFunction.returnType()Lorg/jetbrains/plugins/scala/lang/psi/types/result/TypeResult;
	at com.thangiee.freasymonad.injector.FreeInjector$RichFunc.<init>(FreeInjector.scala:28)
	at com.thangiee.freasymonad.injector.FreeInjector$.RichFunc(FreeInjector.scala:13)
	at com.thangiee.freasymonad.injector.FreeInjector$$anonfun$17.apply(FreeInjector.scala:79)
	at com.thangiee.freasymonad.injector.FreeInjector$$anonfun$17.apply(FreeInjector.scala:79)
	at scala.collection.TraversableLike$$anonfun$partition$1.apply(TraversableLike.scala:314)
	at scala.collection.TraversableLike$$anonfun$partition$1.apply(TraversableLike.scala:314)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.partition(TraversableLike.scala:314)
	at scala.collection.AbstractTraversable.partition(Traversable.scala:104)
	at com.thangiee.freasymonad.injector.FreeInjector$class.injectInners(FreeInjector.scala:79)
	at com.thangiee.freasymonad.injector.CatsFreeInjector.injectInners(CatsFreeInjector.scala:3)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$$anonfun$injectInners$1.apply(SyntheticMembersInjector.scala:119)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$$anonfun$injectInners$1.apply(SyntheticMembersInjector.scala:118)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.injectInners(SyntheticMembersInjector.scala:118)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTypeDefinition$class.syntheticTypeDefinitionsImpl(ScTypeDefinition.scala:70)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.ScTypeDefinitionImpl.syntheticTypeDefinitionsImpl(ScTypeDefinitionImpl.scala:48)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTemplateDefinition$class.syntheticTypeDefinitions(ScTemplateDefinition.scala:173)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.ScTypeDefinitionImpl.syntheticTypeDefinitions(ScTypeDefinitionImpl.scala:48)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$ParameterlessNodes$.processScala(TypeDefinitionMembers.scala:195)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.build(MixinNodes.scala:338)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.build(MixinNodes.scala:310)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.inner$1(TypeDefinitionMembers.scala:509)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.getParameterlessSignatures(TypeDefinitionMembers.scala:511)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$$anonfun$processDeclarations$2.apply(TypeDefinitionMembers.scala:662)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$$anonfun$processDeclarations$2.apply(TypeDefinitionMembers.scala:662)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$Lazy.apply(TypeDefinitionMembers.scala:713)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.privateProcessDeclarations(TypeDefinitionMembers.scala:960)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.processDeclarations(TypeDefinitionMembers.scala:661)
	at org.jetbrains.plugins.scala.lang.resolve.processor.BaseProcessor.processElement(BaseProcessor.scala:296)
	at org.jetbrains.plugins.scala.lang.resolve.processor.BaseProcessor.processType(BaseProcessor.scala:202)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.processQualifierResolveResult(ScStableCodeReferenceElementImpl.scala:344)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.processQualifier(ScStableCodeReferenceElementImpl.scala:323)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.doResolve(ScStableCodeReferenceElementImpl.scala:455)
	at org.jetbrains.plugins.scala.lang.resolve.StableCodeReferenceElementResolver.resolve(StableCodeReferenceElementResolver.scala:41)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.multiResolve(ScStableCodeReferenceElementImpl.scala:283)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.imports.ScImportStmtImpl.workWithImportExpr$1(ScImportStmtImpl.scala:104)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.imports.ScImportStmtImpl.processDeclarations(ScImportStmtImpl.scala:342)
	at org.jetbrains.plugins.scala.lang.psi.ScImportsHolder$class.processDeclarations(ScImportsHolder.scala:60)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.templates.ScTemplateBodyImpl.processDeclarations(ScTemplateBodyImpl.scala:79)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.treeWalkUp$1(ScStableCodeReferenceElementImpl.scala:299)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.processQualifier(ScStableCodeReferenceElementImpl.scala:310)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.doResolve(ScStableCodeReferenceElementImpl.scala:455)
	at org.jetbrains.plugins.scala.lang.resolve.StableCodeReferenceElementResolver.resolve(StableCodeReferenceElementResolver.scala:41)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.multiResolve(ScStableCodeReferenceElementImpl.scala:283)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceElementImpl.bind(ScReferenceElementImpl.scala:35)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.processQualifier(ScStableCodeReferenceElementImpl.scala:322)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.doResolve(ScStableCodeReferenceElementImpl.scala:455)
	at org.jetbrains.plugins.scala.lang.resolve.StableCodeReferenceElementResolver.resolve(StableCodeReferenceElementResolver.scala:41)
	at org.jetbrains.plugins.scala.lang.resolve.ResolvableStableCodeReferenceElement$Ext$.resolveNoConstructor$extension(ResolvableStableCodeReferenceElement.scala:70)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.types.ScSimpleTypeElementImpl.org$jetbrains$plugins$scala$lang$psi$impl$base$types$ScSimpleTypeElementImpl$$innerNonValueType(ScSimpleTypeElementImpl.scala:272)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.types.ScSimpleTypeElementImpl.innerType(ScSimpleTypeElementImpl.scala:39)
	at org.jetbrains.plugins.scala.lang.psi.api.base.types.ScTypeElement$class.getType(ScTypeElement.scala:25)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.types.ScSimpleTypeElementImpl.getType(ScSimpleTypeElementImpl.scala:38)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.types.ScParameterizedTypeElementImpl.innerType(ScParameterizedTypeElementImpl.scala:158)
	at org.jetbrains.plugins.scala.lang.psi.api.base.types.ScTypeElement$class.getType(ScTypeElement.scala:25)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.types.ScParameterizedTypeElementImpl.getType(ScParameterizedTypeElementImpl.scala:29)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.templates.ScClassParentsImpl.superTypes(ScClassParentsImpl.scala:41)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.templates.ScExtendsBlockImpl.superTypes(ScExtendsBlockImpl.scala:81)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTemplateDefinition$class.superTypes(ScTemplateDefinition.scala:190)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScNewTemplateDefinitionImpl.superTypes(ScNewTemplateDefinitionImpl.scala:38)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes$.inner$1(MixinNodes.scala:475)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes$.linearization(MixinNodes.scala:491)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.build(MixinNodes.scala:366)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.build(MixinNodes.scala:310)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.buildNodesClass$1(TypeDefinitionMembers.scala:526)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.getSignatures(TypeDefinitionMembers.scala:528)
	at org.jetbrains.plugins.scala.lang.psi.api.statements.ScFunction$class.superSignaturesIncludingSelfType(ScFunction.scala:461)
	at org.jetbrains.plugins.scala.lang.psi.impl.statements.ScFunctionImpl.superSignaturesIncludingSelfType(ScFunctionImpl.scala:27)
	at org.jetbrains.plugins.scala.annotator.gutter.ScalaLineMarkerProvider.getGatorInfo(ScalaLineMarkerProvider.scala:94)
	at org.jetbrains.plugins.scala.annotator.gutter.ScalaLineMarkerProvider.getLineMarkerInfo(ScalaLineMarkerProvider.scala:44)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:186)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Thangiee** [comment]
If by any chance you are still using Scala 2.11 and a recently updated IntelliJ, check out the meta branch at https://github.com/Thangiee/Freasy-Monad/tree/meta. This branch uses the new scala.meta so the plugin is no longer require. In fact, it needs to be uninstalled. There is a known issue with IntelliJ that causes syntax highlighting issues on 2.12, but everything should work with 2.11 as far as I know.

**Comment by Thangiee** [comment]
Version 0.6.0 no longer needs the freasy-monad plugin. In fact, it needs to be uninstalled.
